# Archivo config.toml para Streamlit

[global]
pageTitle = "Análisis de rentabilidad de expansión hotelera"  # Título de la pestaña

[server]
headless = true  # Esto asegura que no se abra el navegador de manera predeterminada

[theme]
base="black"  # Establece el tema oscuro como predeterminado
primaryColor="#F63366"  # Color principal
backgroundColor="#eeeeee"  # Fondo oscuro de la aplicación
secondaryBackgroundColor="#f5f5dc"  # Fondo del panel secundario
textColor="black"  # Color del texto negro
